name: dart_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^1.0.1
  shelf_logger: ^1.0.0
  json_annotation: ^4.7.0
  dart_json_mapper: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.1
